# Generated by Django 5.2.1 on 2025-06-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'Рассматривается администратором'), ('completed', 'Выполнена'), ('rejected', 'Отклонена')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
